version: '3.7'

services:
  apollo-configservice:
    container_name: apollo-configservice
    image: apolloconfig/apollo-configservice
    volumes:
      - type: volume
        source: logs
        target: /opt/logs
    ports:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.30.131:3306/ApolloConfigDB?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
    restart: always
    network_mode: host

  apollo-adminservice:
    depends_on:
      - apollo-configservice
    container_name: apollo-adminservice
    image: apolloconfig/apollo-adminservice
    volumes:
      - type: volume
        source: logs
        target: /opt/logs
    ports:
      - "8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.30.131:3306/ApolloConfigDB?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
    restart: always
    network_mode: host

  apollo-portal:
    depends_on:
      - apollo-adminservice
    container_name: apollo-portal
    image: apolloconfig/apollo-portal
    volumes:
      - type: volume
        source: logs
        target: /opt/logs
    ports:
      - "8070"
    environment:  
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.30.131:3306/ApolloPortalDB?characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
      - APOLLO_PORTAL_ENVS=dev
      - DEV_META=http://192.168.30.131:8080
    restart: always
    network_mode: host

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/logs