version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - D:/docker_destktop/shareing_dir/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
  # mysql的web客户端
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8089:8080
